# Logs into Azure with OIDC, fetches a secret, echos the MD5
# 1. OIDC docs: https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux
#   a. create app 
#      az ad app create --display-name oidckvApp # save "appId" value as $appId 
#   b. create service principal
#      az ad sp create --id $appId # save "id" value as $assigneeObjectId
#   c. create role assignment
#      az role assignment create --role "Key Vault Secrets User" \
#        --scope "/subscriptions/4706567a-599b-4483-aee4-41926752f05b/resourceGroups/oidc-kv/providers/Microsoft.KeyVault/vaults/oidc-kv1" \
#        --assignee-object-id $assigneeObjectId --assignee-principal-type ServicePrincipal 
#   d. set subject claim
#     az ad app federated-credential create --id $appId --parameters '{
#       "name": "oidckv-cred",
#       "issuer": "https://token.actions.githubusercontent.com",
#       "subject": "repository_owner:ideasyncratic:job_workflow_ref:ideasyncratic/oidckv/.github/workflows/oidckv.yml@refs/heads/main",
#       "description": "Credential for ideasyncratic/oidckv workflow",
#       "audiences": [ "api://AzureADTokenExchange" ] }'
#   e. In the env section below, set AZURE_CLIENT_ID to the $appId and set AZURE_TENANT_ID and AZURE_SUBSCRIPTION_ID
#
# 2. Use like:
#   name: Run oidckv workflow
#   on:
#     issue_comment:
#       types: [created]
#   jobs:
#     call-workflow-passing-data:
#       uses: ideasyncratic/oidckv/.github/workflows/oidckv.yml@main
# 
# 3. Set OIDC subject to include shared workflow and org
#   # org default
#   curl -L \
#     -X PUT \
#     -H "Accept: application/vnd.github+json" \
#     -H "Authorization: Bearer $password"\
#     -H "X-GitHub-Api-Version: 2022-11-28" \
#     https://api.github.com/orgs/ideasyncratic/actions/oidc/customization/sub \
#     -d '{"include_claim_keys":["repository_owner","job_workflow_ref"]}'
#
#   # update existing repos
#   curl -L \
#     -X PUT \
#     -H "Accept: application/vnd.github+json" \
#     -H "Authorization: Bearer $password"\
#     -H "X-GitHub-Api-Version: 2022-11-28" \
#     https://api.github.com/repos/ideasyncratic/oidckv-user/actions/oidc/customization/sub \
#     -d '{"use_default":false,"include_claim_keys":["repository_owner","job_workflow_ref"]}' 
#
#   produces a subject claim like:
#    subject claim - repository_owner:ideasyncratic:job_workflow_ref:ideasyncratic/oidckv/.github/workflows/oidckv.yml@refs/heads/main
# 

name: manual Login with OIDC, fetch a key vault secret, echo

on:
  workflow_dispatch:

jobs:
  echoMd5:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Echo base64 of secret
      run: |
        az login --client-id 9d04cac8-55ab-49e7-88c0-785e0f34f9c0 --tenant cfeeb63b-ccfc-439f-a359-4cdc09697570
        secret=$(az keyvault secret show --subscription 4706567a-599b-4483-aee4-41926752f05b --name api-key --vault-name oidc-kv1 --query value --output tsv)
        echo "$api_key" | base64
